/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HeroTest{
  // @After
  //  public void tearDown() {
  //    Hero.clear();
  //  }
   @Test
public void Hero_InstantiatesCorrectly_true(){
  Hero myHero = new Hero("Batman", 55, "Tech", "joker");
  assertEquals(true, myHero instanceof Hero );
  }
  @Test
  public void Hero_GetName_batman() {
    Hero myHero = new Hero("Batman", 55, "Tech", "joker");
    assertEquals("Batman", myHero.getName());
  }
  @Test
  public void Hero_GetAge_55(){
    Hero myHero = new Hero("Batman", 55, "Tech villain", "joker");
    assertEquals(55, myHero.getAge());
  }
  @Test
  public void Hero_GetPower_Tech(){
    Hero myHero = new Hero("Batman", 55, "Tech", "joker");
    assertEquals("Tech", myHero.getPower());
  }
  @Test
  public void Hero_GetWeakness_joker(){
    Hero myHero = new Hero("Batman", 55, "Tech", "joker");
    assertEquals("joker", myHero.getWeakness());
  }
  @Test
  public void Hero_GetId_0(){
    Hero.clear();
  Hero myHero = new Hero("Batman", 55, "Tech", "joker");
  assertEquals(1, myHero.getId());
}
}
